/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import randomNumbers.Image;

/**
 *
 * @author Hasty
 */
public class jpImage extends javax.swing.JPanel {
    Image img;
    /**
     * Creates new form jpImage
     */
    public jpImage() {
        initComponents();
        jfFile.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfFile = new javax.swing.JFrame();
        jfChooser = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jlResponse = new javax.swing.JLabel();

        jfFile.setTitle("Seleccionar la imagen");
        jfFile.setMinimumSize(new java.awt.Dimension(623, 397));

        jfChooser.setMinimumSize(new java.awt.Dimension(900, 500));
        jfChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfFileLayout = new javax.swing.GroupLayout(jfFile.getContentPane());
        jfFile.getContentPane().setLayout(jfFileLayout);
        jfFileLayout.setHorizontalGroup(
            jfFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(jfFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jfFileLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jfChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jfFileLayout.setVerticalGroup(
            jfFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(jfFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jfFileLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jfChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setPreferredSize(new java.awt.Dimension(900, 500));

        jButton1.setText("Seleccionar imagen");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jlResponse.setText("Respuesta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 757, Short.MAX_VALUE))
                    .addComponent(jlResponse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jlResponse)
                .addContainerGap(434, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        jfFile.show();
    }//GEN-LAST:event_jButton1MousePressed

    private void jfChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfChooserActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
            try {
                jfFile.hide();
                img = new Image();
                img.getPercentage(jfChooser.getSelectedFile(), jlResponse);
            } catch (IOException ex) {
                Logger.getLogger(jpImage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            jfFile.hide();
        }
    }//GEN-LAST:event_jfChooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jfChooser;
    private javax.swing.JFrame jfFile;
    private javax.swing.JLabel jlResponse;
    // End of variables declaration//GEN-END:variables
}
